# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: MPL-2.0

name: hashicorp/packer-plugin-hyperv/build_plugin_binaries
permissions:
  contents: read
on:
  push:
    branches:
    - main
jobs:
  build_windows:
    defaults:
      run:
        working-directory: ~/go/src/github.com/hashicorp/packer-plugin-hyperv
    runs-on: ubuntu-latest
    container:
      image: docker.mirror.hashicorp.services/cimg/go:1.21
    steps:
    - uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4
    - uses: "./.github/actions/build-and-persist-plugin-binary"
      with:
        GOOS: windows
        GOARCH: 386
    - uses: "./.github/actions/build-and-persist-plugin-binary"
      with:
        GOOS: windows
        GOARCH: amd64
